# The location of a snapshot can be provided as a file or url. Stack assumes
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/6.yaml

# User packages to be built
packages:
  - xmonad-git
  - xmonad-contrib-git
  - xmobar-git

# Override default flag values for local packages and extra-deps
flags:
  xmobar:
    with_xft: true
    with_xpm: true
