resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/11.yaml

packages:
  - xmobar-git
  - xmonad-git
  - xmonad-contrib-git

flags:
  xmobar:
    with_xft: true
    with_xpm: true
