resolver: lts-19.23

packages:
  - .

extra-deps:
  - github: xmonad/x11
    commit: 3f6e53cb81abf624bb3de1749b3d46c0aa205ad1
  - github: xmonad/xmonad
    commit: e3cd2b26e2b1bbcf30df5598af5324785f5ac6a6
  - github: xmonad/xmonad-contrib
    commit: 81c3cbc289e842855b632144fa7a964c8c0fc24c
  - xmobar-0.44.2

flags:
  xmobar:
    with_xpm: true
    with_threaded: true
    with_xft: true
    with_rtsopts: true

arch: x86_64
