resolver: lts-19.23

packages:
  - . 

extra-deps:
  - github: xmonad/x11
    commit: 8a33c4ebe7d0a1be96073d8c019f1f3901bbf344					
  - github: xmonad/xmonad
    commit: 1aac6611d82065c9198e5584176058a9483fcbb0					
  - github: xmonad/xmonad-contrib
    commit: 4d0f3ee9444bb998e0831fc381953466b6d3ecdf					
  - xmobar-0.44.2

flags:
  xmobar:
    with_xpm: true
    with_threaded: true
    with_xft: true
    with_rtsopts: true

arch: x86_64
