resolver: lts-19.23

packages:
  - . 

extra-deps:
  - github: xmonad/x11
    commit: 7512f74eae88540f854759f77a0c0160734c4e77					
  - github: xmonad/xmonad
    commit: ebf265a84c6295d4fe15c4a5cf88cb08746f2145					
  - github: xmonad/xmonad-contrib
    commit: 4b866210512b90bc532b4cd46dc5171542d0fac8					
  - xmobar-0.44.2

flags:
  xmobar:
    with_xpm: true
    with_threaded: true
    with_xft: true
    with_rtsopts: true

arch: x86_64
