#!/bin/bash

LATESTXMONAD=$(git ls-remote https://github.com/xmonad/xmonad.git HEAD | sed "s/HEAD//")
LATESTCONTRIB=$(git ls-remote https://github.com/xmonad/xmonad-contrib.git HEAD | sed "s/HEAD//")
LATESTX11=$(git ls-remote https://github.com/xmonad/x11.git HEAD | sed "s/HEAD//")

CURRENTXMONAD=$(awk '/xmonad[/]xmonad$/{getline;print$2}' ./stack.yaml)
CURRENTCONTRIB=$(awk '/xmonad[/]xmonad-contrib$/{getline;print$2}' ./stack.yaml)
CURRENTX11=$(awk '/xmonad[/]x11$/{getline;print$2}' ./stack.yaml)

if [[ "$LATESTXMONAD" != "$CURRENTXMONAD" ]] ; then 
	sed -i "s/${CURRENTXMONAD}/${LATESTXMONAD}/" ./stack.yaml
	printf "XMonad upgraded to latest.\n"
else
	printf "XMonad is up to date.\n"
fi

if [[ "$LATESTCONTRIB" != "$CURRENTCONTRIB" ]] ; then 
	sed -i "s/${CURRENTCONTRIB}/${LATESTCONTRIB}/" ./stack.yaml
	printf "XMonad-Contrib upgraded to latest\n"
else
	printf "XMonad-Contrib is up to date.\n"
fi

if [[ "$LATESTX11" != "$CURRENTX11" ]] ; then
	sed -i "s/${CURRENTX11}/${LATESTX11}/" ./stack.yaml
	printf "X11 upgraded to latest.\n"
else
	printf "X11 is up to date.\n"
fi
