[[colors.indexed_colors]]
color = "0xd19a66"
index = 16

[[colors.indexed_colors]]
color = "0xbe5046"
index = 17

[[colors.indexed_colors]]
color = "0x353b45"
index = 18

[[colors.indexed_colors]]
color = "0x3e4451"
index = 19

[[colors.indexed_colors]]
color = "0x565c64"
index = 20

[[colors.indexed_colors]]
color = "0xb6bdca"
index = 21

[colors.bright]
black = "0x545862"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xc8ccd4"
yellow = "0xe5c07b"

[colors.cursor]
cursor = "0xabb2bf"
text = "0x282c34"

[colors.dim]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.normal]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[cursor]
style = { shape = "Underline", blinking = "On" }

[env]
TERM = "alacritty"

[font]
normal = { family = "IBM Plex Mono", style = "Medium" }
bold   = { family = "IBM Plex Mono", style = "Bold"   }
size   = 12 

[terminal.shell]
program = "/bin/bash"

[window]
opacity = 1.0
dynamic_padding = true
padding = { x = 8, y = 4 }
